# Generated by Django 5.1.4 on 2025-01-02 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0006_remove_author_vachanas_author_vachanas'),
        ('vachanas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vachana',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vachanas_written', to='authors.author'),
        ),
    ]
