# Generated by Django 5.1.4 on 2024-12-24 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        ('vachanas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='vachanas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='vachanas.vachana'),
        ),
    ]
