# Generated by Django 5.1.4 on 2025-01-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_alter_author_photo'),
        ('vachanas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='vachanas',
        ),
        migrations.AddField(
            model_name='author',
            name='vachanas',
            field=models.ManyToManyField(blank=True, related_name='authors', to='vachanas.vachana'),
        ),
    ]
