# Generated by Django 5.1.4 on 2025-01-02 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_remove_author_vachanas_author_vachanas'),
        ('vachanas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='vachanas',
        ),
        migrations.AddField(
            model_name='author',
            name='vachanas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='vachanas.vachana'),
        ),
    ]
